### ISSUE TITLE
Supplementary Data Checklist

### ISSUE THREAD

**Issue by DimmestP** [DimmestP/chimera_project_manuscript#79]
- [x] TSA1 Secondary Structure
- [x] RPS3 Secondary Structure
- [x] PIR1 Secondary structure
- [ ] Selecting PIR1 Decision Tree/Table
- [ ] Selecting TSA1 Decision Tree/Table
- [ ] 69 to 4 Motif Selection Table

**Comment by ewallace** [comment]
I think this is now addressed? In many cases we have decided we don't need them, e.g. a full decision tree.
